### ISSUE TITLE
Not gain drops :c

### ISSUE THREAD

**Issue by igoutta** [mannguyen0107/LazyFishing#4]
I do everything as you say, but when I fishing and the lure is jumping the drop don't appear. i really don't now if it's the address or the method of fishing code.

Troubles away, looks this code its very efficent and certainly short without address input. Works trully great, sadly the developer no longer update the code. https://github.com/howar31/Trove-AHK-AutoFish

**Comment by mannguyen0107** [comment]
^ that bot do use address and everytime game update you should update address which you can get if you follow instruction on my MPGH post also if I cant update the address on the forum there are alwasy ppl update it
