### ISSUE TITLE
Update...

### ISSUE THREAD

**Issue by Kulitorum** [mannguyen0107/LazyFishing#5]
I have worked on your script and added some nice features, such as:

check if a slot is empty before deconstruction or boot throwing
Scalable windows, so you can set the size of the windows
...maybe more...

Do you want to take a look at these changes, or do you have the same code almost ready?

**Comment by mannguyen0107** [comment]
oh Nice sorry i have been off from this project for a long time but if you still working on this please fork it and i will merge it for you
